language: python
python:
- 3.6
- 3.5
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: davewd
  password:
    secure: mjNQSjg+a8sajVaG5rdROfnE0DWgAyn/3Zzb4u7r/7/6/9ixv8XvcTvHhzJ5uG9mMyT3Tgk2yisiJDcR7qF/vEb17vahCKGb32vgnLWVjaiYEpN4/ePGbvl3QKO8+sGljp2XYQzX0CZAiQvXGzwq4dkjKNULDojAD0J03whGTDqq2rfEmTQHZyKenPFGs6cjiU+TCTFQCf9wsJmTFsSIQfmbBXbya9oEmSOJyUL64AEUCJ+ryJQnc44M1TFhlwcLfQ5bOjRXe9EAvn/zo5GzrC2RzufQvQUj8B+T8DSRg/KPnvxzuHFAYfeSAGdxQqDis4Bb8mpVZVmlzGJ+T1Ov6yAWge7+dLhW42BgsbNF4h2doRJnYD8MR3N8EVj7GWZHpjDOuIGHEjUACsUTrvjp1znEGzP6dPI8sDrmVVnIfltH1i4hYTnmKO/wtIQZ2Asy27GgsAwKL/J6TZ6KL3mFDTAIVqsbQjEFFZs1u4jUyXOuGcRd3HmGBpJOJYFT/ozVxafpdKkaJvKKG5T+6Bzuer3FpAHWtXUyV3uNkFsMJEKhZUDpkZAYxqjriahMixSOuF+fNOR2Isf7a5YNizr8hdr5EIGBQ/aK5SjjGKHHz8yR5Ezka9RoVDB3xAwcpj4fKVWTXiiexmyrukeltQkYh0LsGheO6L/9Ra59bjEZZEE=
  on:
    tags: true
    repo: davewd/sho
    python: 3.6
after_success:
  - pip install codecov
  - codecov
